/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.edusys.ui;

import com.edusys.dao.EduSystemDAO;
import com.edusys.dao.StaffDAO;
import com.edusys.entity.Staff;

import static com.edusys.ui.Home.isHomeOpened;
import static com.edusys.ui.Main.isMainOpened;

import com.edusys.swing.FileChooser;
import com.edusys.utils.AESUtil;

import com.edusys.utils.AppConfig;
import com.edusys.utils.Auth;
import com.edusys.utils.MsgBox;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import org.opencv.core.Core;

import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;

import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import java.awt.image.BufferedImage;
import java.io.File;
import java.security.MessageDigest;

/**
 * @author ngocd
 */
public class Login extends javax.swing.JDialog {

    StaffDAO dao = new StaffDAO();

    /**
     * Creates new form DangNhap
     */
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        loadConfig();
        setAlwaysOnTop(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        btnForgotPass = new javax.swing.JButton();
        btnDangNhap = new javax.swing.JButton();
        cbRemember = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblFaceId = new javax.swing.JLabel();
        lblQR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đăng Nhập");

        jPanel2.setBackground(new java.awt.Color(217, 237, 191));
        jPanel2.setForeground(new java.awt.Color(123, 188, 196));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/book_open.gif"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(123, 188, 196));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(123, 188, 196));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đăng nhập");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(123, 188, 196));
        jLabel3.setText("Tên đăng nhập:");

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsername.setAutoscrolls(false);
        txtUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsername.setFocusCycleRoot(true);
        txtUsername.setFocusTraversalPolicyProvider(true);
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(123, 188, 196));
        jLabel4.setText("Mật khẩu:");

        txtPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassKeyReleased(evt);
            }
        });

        btnForgotPass.setBackground(new java.awt.Color(217, 237, 191));
        btnForgotPass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnForgotPass.setForeground(new java.awt.Color(123, 188, 196));
        btnForgotPass.setText("Quên mật khẩu ?");
        btnForgotPass.setBorder(null);
        btnForgotPass.setContentAreaFilled(false);
        btnForgotPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnForgotPass.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnForgotPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgotPassActionPerformed(evt);
            }
        });

        btnDangNhap.setBackground(new java.awt.Color(90, 139, 145));
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(217, 237, 191));
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        cbRemember.setBackground(new java.awt.Color(217, 237, 191));
        cbRemember.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbRemember.setForeground(new java.awt.Color(123, 188, 196));
        cbRemember.setText("Remember me");
        cbRemember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setBackground(new java.awt.Color(217, 237, 191));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(123, 188, 196));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("HOẶC");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(123, 188, 196));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/fb64.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblFaceId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFaceId.setForeground(new java.awt.Color(123, 188, 196));
        lblFaceId.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/face-id.png"))); // NOI18N
        lblFaceId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFaceId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFaceIdMouseClicked(evt);
            }
        });

        lblQR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/qr-code.png"))); // NOI18N
        lblQR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblQR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQRMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUsername)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtPass)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(cbRemember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(btnForgotPass))
                    .addComponent(btnDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFaceId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblQR)
                        .addGap(18, 18, 18)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnForgotPass)
                    .addComponent(cbRemember))
                .addGap(18, 18, 18)
                .addComponent(btnDangNhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lblQR)
                    .addComponent(lblFaceId))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnForgotPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgotPassActionPerformed
        // TODO add your handling code here:
        new ForgotPass((Frame) getOwner(), true).setVisible(true);
    }//GEN-LAST:event_btnForgotPassActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        loginEvt();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void lblQRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQRMouseClicked
        // TODO add your handling code here:
        QRcodeLogin();
    }//GEN-LAST:event_lblQRMouseClicked

    private void txtUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyReleased
        // TODO add your handling code here:
        KeyEnter(evt);
    }//GEN-LAST:event_txtUsernameKeyReleased

    private void txtPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyReleased
        // TODO add your handling code here:
        KeyEnter(evt);
    }//GEN-LAST:event_txtPassKeyReleased

    private void lblFaceIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFaceIdMouseClicked
        // TODO add your handling code here:
        new FaceDetection((Frame) getOwner(), true).setVisible(true);
    }//GEN-LAST:event_lblFaceIdMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login dialog = new Login(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnForgotPass;
    private javax.swing.JCheckBox cbRemember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFaceId;
    private javax.swing.JLabel lblQR;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void loginEvt() {
        String user = txtUsername.getText();
        String pass = String.valueOf(txtPass.getPassword());
        boolean remember = cbRemember.isSelected();
        if (remember) {
            AppConfig.saveConfig(user, pass, remember);
        } else {
            AppConfig.clear();
        }
        Staff nv = dao.selectById(user);
        if (nv == null || !pass.equalsIgnoreCase(nv.getPass())) {
            MsgBox.alert(this, "Tên đăng nhập hoặc mật khẩu không chính xác!");
        } else {
            Auth.user = nv;
            this.dispose();
            if (!isHomeOpened) {
                new Home().setVisible(true);
                isHomeOpened = true;  // Đánh dấu rằng Home đã được mở
            }
            if (!isMainOpened) {
                new Main().setVisible(true);
                isMainOpened = true;
            }

        }
    }

    private void loadConfig() {
        AppConfig config = AppConfig.loadConfig();
        txtUsername.setText(config.getUser());
        txtPass.setText(config.getPass());
        cbRemember.setSelected(config.isRemember());
    }

    private void QRcodeLogin() {
//        AppConfig.clear();
        try {
            FileChooser fileChooser = new FileChooser("config");
            int result = fileChooser.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                BufferedImage qrcode = ImageIO.read(file);
                LuminanceSource source = new BufferedImageLuminanceSource(qrcode);
                BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
                Result qrResult = new MultiFormatReader().decode(bitmap);

                // Mã hóa QR
                try {
                    String data = AESUtil.decrypt(qrResult.getText());

                    // Kiểm tra thông tin
                    String[] userInfor = data.split(",");
                    String user = userInfor[0];
                    String pass = userInfor[1];

                    Staff nv = dao.selectById(user);
                    if (nv == null && !pass.equalsIgnoreCase(nv.getPass())) {
                        MsgBox.alert(this, "Mã QR không chính xác.");
                    } else {
                        Auth.user = nv;
                        this.dispose();
                        if (!isHomeOpened) {
                            new Home().setVisible(true);
                            isHomeOpened = true;  // Đánh dấu rằng Home đã được mở
                        }
                        if (!isMainOpened) {
                            new Main().setVisible(true);
                            isMainOpened = true;
                        }
                    }
                } catch (Exception e) {
                    MsgBox.alert(this, "Mã QR không hợp lệ");
                }
            }
        } catch (Exception e) {
            MsgBox.alert(this, "File không hợp lệ");
//            throw new RuntimeException(e);
        }
    }

    private void KeyEnter(KeyEvent e) {
        if (e.getKeyCode() == KeyEvent.VK_ENTER) {
            loginEvt();
        }
    }

}
