/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.edusys.form;

import java.awt.Desktop;
import java.net.URI;

/**
 *
 * @author ngocd
 */
public class Infor_Form extends javax.swing.JPanel {

    /**
     * Creates new form Infor_Form
     */
    public Infor_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPic = new javax.swing.JLabel();
        lblFB = new javax.swing.JLabel();
        lblYT = new javax.swing.JLabel();
        lblDiscord = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 242, 242));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(123, 188, 196));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("~~~~ Đinh Quốc Bảo Khang ~~~~");
        jLabel2.setToolTipText("");
        jLabel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLabel2.setDoubleBuffered(true);
        jLabel2.setFocusTraversalPolicyProvider(true);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(123, 188, 196));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("@yuno.k - khangdqbps36645@fpt.edu.vn");
        jLabel8.setToolTipText("");
        jLabel8.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLabel8.setDoubleBuffered(true);
        jLabel8.setFocusTraversalPolicyProvider(true);

        lblPic.setBackground(new java.awt.Color(242, 242, 242));
        lblPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/im_the_best.gif"))); // NOI18N

        lblFB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/facebook.png"))); // NOI18N
        lblFB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFBMouseClicked(evt);
            }
        });

        lblYT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/youtube.png"))); // NOI18N
        lblYT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblYT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblYTMouseClicked(evt);
            }
        });

        lblDiscord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/discord.png"))); // NOI18N
        lblDiscord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDiscord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDiscordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDiscord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblYT))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblYT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDiscord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblFBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFBMouseClicked
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URI("https://www.facebook.com/Yuno1z2t/"));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_lblFBMouseClicked

    private void lblDiscordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDiscordMouseClicked
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URI("https://discord.gg/P5g8vAerbN"));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_lblDiscordMouseClicked

    private void lblYTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblYTMouseClicked
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URI("https://www.youtube.com/channel/UC2P6YTrAHeuXg6tDCSwqt9g"));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_lblYTMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblDiscord;
    private javax.swing.JLabel lblFB;
    private javax.swing.JLabel lblPic;
    private javax.swing.JLabel lblYT;
    // End of variables declaration//GEN-END:variables
}
